class Projection < ActiveRecord::Base
  def initialize(hash)
    @week = hash['week']
    @playerId = hash['playerId']
    @position = hash['position']
    @passAtt = hash['passAtt']
    @passCmp = hash['passCmp']
    @passYds = hash['passYds']
    @passTD = hash['passTD']
    @passInt = hash['passInt']
    @rushAtt = hash['rushAtt']
    @rushYds = hash['rushYds']
    @rushTD = hash['rushTD']
    @fumblesLost = hash['fumblesLost']
    @receptions = hash['receptions']
    @recYds = hash['recYds']
    @recTD = hash['recTD']
    @fg = hash['fg']
    @fgAtt = hash['fgAtt']
    @xp = hash['xp']
    @defInt = hash['defInt']
    @defFR = hash['defFR']
    @defFF = hash['defFF']
    @defSack = hash['defSack']
    @defTD = hash['defTD']
    @defRetTD = hash['defRetTD']
    @defSafety = hash['defSafety']
    @defPA = hash['defPA']
    @defYdsAllowed = hash['defYdsAllowed']
    @displayName = hash['displayName']
    @team = hash['team']
  end
end
